import type { Metadata } from "next";
import Link from "next/link";
import { getAdminNovels } from "@/lib/admin-data";

export const metadata: Metadata = { title: "Kelola novel", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";
export const revalidate = 0;

export default async function AdminNovelsPage() {
  const { novels, error } = await getAdminNovels();
  return <section className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/admin" className="text-sm font-bold text-[var(--accent)] hover:underline">← Dashboard admin</Link><h1 className="mt-3 font-[family-name:var(--font-lora)] text-4xl font-bold">Novel & bab</h1></div><Link href="/admin/novels/new" className="inline-flex min-h-11 items-center rounded-full bg-[var(--accent)] px-5 text-sm font-bold text-white">Buat novel</Link></div>{error && <p role="status" className="mt-6 rounded-xl bg-red-500/10 p-4 text-sm text-red-800">{error}</p>}{novels.length ? <div className="mt-9 overflow-x-auto rounded-2xl border border-[var(--border)] bg-[var(--surface)]"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-[var(--border)] text-[var(--muted)]"><tr><th className="p-4 font-bold">Novel</th><th className="p-4 font-bold">Status</th><th className="p-4 font-bold">Bab</th><th className="p-4 font-bold">Genre</th><th className="p-4"><span className="sr-only">Aksi</span></th></tr></thead><tbody>{novels.map((novel) => <tr key={novel.id} className="border-b border-[var(--border)] last:border-0"><td className="p-4"><p className="font-bold">{novel.title}</p><p className="mt-1 text-xs text-[var(--muted)]">{novel.authorName} · /{novel.slug}</p></td><td className="p-4"><span className={novel.status === "published" ? "rounded-full bg-emerald-500/10 px-2.5 py-1 text-xs font-bold text-emerald-800" : "rounded-full bg-amber-500/10 px-2.5 py-1 text-xs font-bold text-amber-800"}>{novel.status === "published" ? "Terbit" : "Draft"}</span></td><td className="p-4">{novel.chapterCount}</td><td className="p-4 text-[var(--muted)]">{novel.genres.join(", ") || "—"}</td><td className="p-4 text-right"><Link href={`/admin/novels/${novel.id}`} className="font-bold text-[var(--accent)] hover:underline">Kelola</Link></td></tr>)}</tbody></table></div> : <div className="mt-9 rounded-2xl border border-dashed border-[var(--border)] p-8 text-center"><h2 className="font-[family-name:var(--font-lora)] text-2xl font-bold">Belum ada novel</h2><p className="mt-2 text-sm text-[var(--muted)]">Mulai dengan membuat novel pertama.</p></div>}</section>;
}
